inferse/Models/Code.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace inferse.Models
{
    public class Code
    {
        public int CodeId { get; set; }
        public string Post { get; set; }
        public System.DateTime PostedOn { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime LastModified { get; set; }
        public int UserId { get; set; }

        public virtual UserProfile User { get; set; }
    }
}

inferse/Controllers/CodeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using inferse.Models;
using inferse.Filters;
using inferse.Helpers;

namespace inferse.Controllers
{
    public class CodeController : BaseController
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Default1/

        public ActionResult Index()
        {
            var codes = db.Codes.Include(c => c.User);
            return View(codes.ToList());
        }

        //
        // GET: /Default1/Details/5

        public ActionResult Details(int id = 0)
        {
            Code code = db.Codes.Find(id);
            if (code == null)
            {
                return HttpNotFound();
            }
            return View(code);
        }

        //
        // GET: /Default1/Create

        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Default1/Create

        [HttpPost]
        public ActionResult Create(Code code)
        {
            if (ModelState.IsValid)
            {
                db.Codes.Add(code);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", code.UserId);
            return View(code);
        }

        //
        // GET: /Default1/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Code code = db.Codes.Find(id);
            if (code == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", code.UserId);
            return View(code);
        }

        //
        // POST: /Default1/Edit/5

        [HttpPost]
        public ActionResult Edit(Code code)
        {
            if (ModelState.IsValid)
            {
                db.Entry(code).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", code.UserId);
            return View(code);
        }

        //
        // GET: /Default1/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Code code = db.Codes.Find(id);
            if (code == null)
            {
                return HttpNotFound();
            }
            return View(code);
        }

        //
        // POST: /Default1/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Code code = db.Codes.Find(id);
            db.Codes.Remove(code);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [InitializeSimpleMembership]
        public ActionResult Home(int? page, int id = 0)
        {
            if (WebMatrix.WebData.WebSecurity.IsAuthenticated)
            {
                UserProfile user = db.UserProfiles.Find(WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name));

                if (!Extensions.IsMyWall(id, user.UserId) && id != 0)
                {
                    UserProfile friend = db.UserProfiles.Find(id);
                    if (user.Following.Contains(friend))
                    {
                        ViewBag.Followship = "Following";
                    }
                    else
                    {
                        ViewBag.Followship = "Follow";
                    }

                    ViewBag.UserProfile = friend;
                    ViewBag.PostsCount = db.Codes.Where(c => c.UserId == friend.UserId).Count().ToString();
                    ViewBag.FollowerCount = friend.Followers.Count.ToString();
                    ViewBag.FollowingCount = friend.Following.Count.ToString();

                    return View(GetPagedCodes(page, friend.UserId));
                }
                else
                {
                    ViewBag.UserProfile = user;
                    ViewBag.PostsCount = db.Codes.Where(c => c.UserId == user.UserId).Count().ToString();
                    ViewBag.FollowerCount = user.Followers.Count.ToString();
                    ViewBag.FollowingCount = user.Following.Count.ToString();

                    return View(GetPagedCodes(page));
                }
            }
            else
            {
                UserProfile user = db.UserProfiles.Find(id);
                ViewBag.UserProfile = user;
                ViewBag.PostsCount = db.Codes.Where(c => c.UserId == user.UserId).Count().ToString();
                ViewBag.FollowerCount = user.Followers.Count.ToString();
                ViewBag.FollowingCount = user.Following.Count.ToString();

                return View(GetPagedCodes(page, db.UserProfiles.Find(id).UserId));
            }
        }

        [InitializeSimpleMembership]
        [HttpPost, ActionName("CodeBox")]
        public ActionResult CodeBox(Code code)
        {
            code.IsDeleted = false;
            code.LastModified = DateTime.Now;
            code.PostedOn = DateTime.Now;

            int userId = WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name);
            code.User = db.UserProfiles.Find(userId);

            if (ModelState.IsValid)
            {
                db.Codes.Add(code);
                db.SaveChanges();
            }
            ModelState.Clear();

            return Content("You post has been publsihed", "text/html");
        }

        [InitializeSimpleMembership]
        [HttpPost, ActionName("Home")]
        public ActionResult Home(int? page, Code code)
        {
            code.IsDeleted = false;
            code.LastModified = DateTime.Now;
            code.PostedOn = DateTime.Now;

            int userId = WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name);
            code.User = db.UserProfiles.Find(userId);

            if (ModelState.IsValid)
            {
                db.Codes.Add(code);
                db.SaveChanges();
            }
            UserProfile user = db.UserProfiles.Find(userId);
            ViewBag.UserProfile = user;

            var codes = GetPagedCodes(page);

            if (codes == null)
                return HttpNotFound();

            //  ViewBag.Codes = codes;

            return View(codes);
        }

    
        public PartialViewResult Followship(int id=0)
        {
            var user = db.UserProfiles.Find(WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name));

            UserProfile friend = db.UserProfiles.Find(id);

            if (user.Following.Contains(friend))
            {
                user.Following.Remove(friend);
                ViewBag.Followship = "Follow";
            }
            else
            {
                user.Following.Add(friend);
                ViewBag.Followship = "Following";
            }
            db.SaveChanges();

            ViewBag.UserProfile = friend;

            var codes = db.Codes.Where(c => c.UserId == friend.UserId || c.Post.Contains("@" + friend.UserName)).OrderByDescending(c => c.PostedOn);
            return PartialView("Followship");
            //return  Content((string)ViewBag.Followship);
        }
        [InitializeSimpleMembership]
        public ActionResult Profile(int? page, int id = 0)
        {
            if (WebMatrix.WebData.WebSecurity.IsAuthenticated)
            {
                UserProfile user = db.UserProfiles.Find(WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name));

                if (!Extensions.IsMyWall(id, user.UserId) && id != 0)
                {
                    UserProfile friend = db.UserProfiles.Find(id);
                    if (user.Following.Contains(friend))
                    {
                        ViewBag.Followship = "Following";
                    }
                    else
                    {
                        ViewBag.Followship = "Follow";
                    }

                    ViewBag.UserProfile = friend;
                    ViewBag.PostsCount = db.Codes.Where(c => c.UserId == friend.UserId).Count().ToString();
                    ViewBag.FollowerCount = friend.Followers.Count.ToString();
                    ViewBag.FollowingCount = friend.Following.Count.ToString();

                    return View(GetPagedCodes(page, friend.UserId));
                }
                else
                {
                    ViewBag.UserProfile = user;
                    ViewBag.PostsCount = db.Codes.Where(c => c.UserId == user.UserId).Count().ToString();
                    ViewBag.FollowerCount = user.Followers.Count.ToString();
                    ViewBag.FollowingCount = user.Following.Count.ToString();

                    return View(GetPagedCodes(page,user.UserId));
                }
            }
            else
            {
                UserProfile user = db.UserProfiles.Find(id);
                ViewBag.UserProfile = user;
                ViewBag.PostsCount = db.Codes.Where(c => c.UserId == user.UserId).Count().ToString();
                ViewBag.FollowerCount = user.Followers.Count.ToString();
                ViewBag.FollowingCount = user.Following.Count.ToString();

                return View(GetPagedCodes(page, db.UserProfiles.Find(id).UserId));
            }
        }

        [InitializeSimpleMembership]
        public ActionResult Mention(int? page)
        {
                int loginUserId = WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name);
                UserProfile user = db.UserProfiles.Where(x => x.UserId == loginUserId).FirstOrDefault();

                ViewBag.UserProfile = user;

                // var codes = db.Codes.Where(c => c.UserId == user.UserId || c.Post.Contains("@" + user.UserName)).OrderByDescending(c => c.PostedOn);         

inferse/Controllers/HomeController.cs
using inferse.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace inferse.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";
            //var context = new UsersContext();
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

inferse/Views/Code/CodeBox.cshtml
    @Styles.Render("~/Content/themes/base/css")
       
    @Scripts.Render("~/bundles/jquery")    
    @Scripts.Render("~/bundles/jqueryui")  
@if(WebMatrix.WebData.WebSecurity.IsAuthenticated)
            {
                 using (Ajax.BeginForm("CodeBox", "Code", new AjaxOptions{ UpdateTargetId = "confirmation", OnSuccess="Clear"}))
                 {
                    @Html.ValidationSummary(true)
                        <fieldset class="ui-widget">
                            <legend>What's heppening</legend>
                            <textarea name="post" id="post-text-box"  ></textarea>
                            <input type="submit" value="Post" class="post-button" data-val="true" data-val-date="The field PostedOn must be a date." data-val-required="The PostedOn field is required."  />
                        </fieldset>
                 }
            }
<div id="confirmation"></div>

<script type="text/javascript">
    $(function () {
        $("#post-text-box").autocomplete({
            source: '@Url.Action("FollowingSearch")',

        });
    });
    function Clear() {
        document.getElementById("post-text-box").value = "";

        setTimeout(function () {
            $('#confirmation').fadeOut();
        }, 5000);

    }
</script>
<script src="~/Scripts/jquery-ui.autocompleteTrigger.js"></script>

inferse/Views/Code/Create.cshtml
@model inferse.Models.Code

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Code</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Post)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Post)
            @Html.ValidationMessageFor(model => model.Post)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PostedOn)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PostedOn)
            @Html.ValidationMessageFor(model => model.PostedOn)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsDeleted)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsDeleted)
            @Html.ValidationMessageFor(model => model.IsDeleted)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastModified)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastModified)
            @Html.ValidationMessageFor(model => model.LastModified)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId, "User")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

inferse/Views/Code/Delete.cshtml
@model inferse.Models.Code

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Code</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Post)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Post)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PostedOn)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostedOn)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsDeleted)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsDeleted)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastModified)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastModified)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.UserName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

inferse/Views/Code/Details.cshtml
@model inferse.Models.Code

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Code</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Post)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Post)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PostedOn)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostedOn)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsDeleted)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsDeleted)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastModified)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastModified)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.UserName)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.CodeId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

inferse/Views/Code/Edit.cshtml
@model inferse.Models.Code

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Code</legend>

        @Html.HiddenFor(model => model.CodeId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Post)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Post)
            @Html.ValidationMessageFor(model => model.Post)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PostedOn)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PostedOn)
            @Html.ValidationMessageFor(model => model.PostedOn)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsDeleted)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsDeleted)
            @Html.ValidationMessageFor(model => model.IsDeleted)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastModified)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastModified)
            @Html.ValidationMessageFor(model => model.LastModified)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId, "User")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

inferse/Views/Code/Home.cshtml
@model IEnumerable<inferse.Models.Code>
@{
    ViewBag.Title = "Wall";
}
@using inferse.Helpers;
@using PagedList;
@using PagedList.Mvc;
@using System.Text.RegularExpressions;
@Styles.Render("~/Content/PagedList.css")

@{
    int userId = Convert.ToInt32(ViewContext.RouteData.Values["id"]);
    int loginUserId = WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name);

    Boolean isMyWall;
    if (userId == loginUserId || userId == 0)
    {
        isMyWall = true;
    }
    else
    {
        isMyWall = false;
    }
}

<div id="dashboard">
    <div class="mini-profile module">
        <div id="profile-summary" class="module-item">
            <h2>
                @ViewBag.UserProfile.Name
            </h2>
            <b class="username">
              @string.Format("{0}" + ViewBag.UserProfile.UserName, "@")
            </b>
            <small>@Html.ActionLink("View complete profile", "Profile", new { id = ViewBag.UserProfile.UserId})</small>
        </div>

        <div id="profile-stats" class="module-item">
            <ul>
                <li><b>@Html.ActionLink((string)ViewBag.PostsCount, "Profile", new { id = ViewBag.UserProfile.UserId})</b><br /><small>Posts</small></li>
                <li><b>@Html.ActionLink((string)ViewBag.FollowerCount, "Follower", "Account", new { id = ViewBag.UserProfile.UserId}, null)</b><br /><small>Follower</small></li>
                <li><b>@Html.ActionLink((string)ViewBag.FollowingCount, "Following", "Account", new { id = ViewBag.UserProfile.UserId}, null)</b><br /><small>Following</small></li>
            </ul>
        </div>

        <div id="post-box" class="module-item">
            @Html.Partial("CodeBox")
        </div>
    </div>
</div>


<div id="timeline">
    <div class="content-header">
          <h2>Timeline</h2>
    </div>
  <ul id="posts">
       @foreach (var item in Model) {
  
            <li class="stream-item">
                <figure>
                    @if(item.User.ProfileImageUrl != null)
                    {
                        @Html.Image(Url.Content("~/Uploads/" + item.User.ProfileImageUrl + "?width=48&height=48"), "Profile Picture", "48")
                    }
                    else
                    {
                        @Html.Image(Url.Content("~/Uploads/avatar.png" + "?width=48&height=48"), "Profile Picture", "48")
                    }
                </figure>
                <article>
                    <header>
                        @if(item.User.Name!= null)
                        {
                             <b>@Html.ActionLink(item.User.Name, "Profile", "Code" ,new { id= item.UserId }, null)</b>
                        }
                        <small>@Html.ActionLink(string.Format("{0}" + item.User.UserName,"@"), "Profile", "Code", new { id= item.UserId }, null)</small>
                    </header>
                    <div class="content">
                         @Html.DisplayFor(modelItem => item.Post)
                         @{if(item.Post != null)
                           {
                               string post = item.Post.ToString();
                               foreach (System.Text.RegularExpressions.Match m in System.Text.RegularExpressions.Regex.Matches(post, "http://(\\S+?)\\.(jpg|png|gif)"))
                               {
                                   @Html.Image("~" + m.Groups[1].Value.ToString() + "?width=72&height=72", "Image", "30")
                               }
                           }
                         }
                    </div>
                    <footer>
                        <small>@Html.Timeago(item.PostedOn)</small>
                    </footer>
                </article>
                <div class="clear-fix"></div>
            </li>
 
        }
   </ul>
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Home", new { page }))
</div>

inferse/Views/Code/Index.cshtml
@model IEnumerable<inferse.Models.Code>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Post)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastModified)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.UserName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Post)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsDeleted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastModified)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.UserName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CodeId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CodeId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CodeId })
        </td>
    </tr>
}

</table>

inferse/Views/Code/Mention.cshtml
@model IEnumerable<inferse.Models.Code>
@{
    ViewBag.Title = "Wall";
}
@using inferse.Helpers;
@using PagedList;
@using PagedList.Mvc;
@Styles.Render("~/Content/PagedList.css")

@{
    int userId = Convert.ToInt32(ViewContext.RouteData.Values["id"]);
    int loginUserId = WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name);

    Boolean isMyWall;
    if (userId == loginUserId || userId == 0)
    {
        isMyWall = true;
    }
    else
    {
        isMyWall = false;
    }
}

<div id="dashboard">
    <div class="mini-profile module">
        <div id="profile-summary" class="module-item">
            <h2>
                @ViewBag.UserProfile.Name
            </h2>
            <b class="username">
              @string.Format("{0}" + ViewBag.UserProfile.UserName, "@")
            </b>
            <small>@Html.ActionLink("View complete profile", "Profile", new { id = ViewBag.UserProfile.UserId})</small>
        </div>

        <div id="profile-stats" class="module-item">
            <ul>
                <li><b>@Html.ActionLink((string)ViewBag.PostsCount, "Profile", new { id = ViewBag.UserProfile.UserId})</b><br /><small>Posts</small></li>
                <li><b>@Html.ActionLink((string)ViewBag.FollowerCount, "Follower", "Account", new { id = ViewBag.UserProfile.UserId}, null)</b><br /><small>Follower</small></li>
                <li><b>@Html.ActionLink((string)ViewBag.FollowingCount, "Following", "Account", new { id = ViewBag.UserProfile.UserId}, null)</b><br /><small>Following</small></li>
            </ul>
        </div>

        <div id="post-box" class="module-item">
            @Html.Partial("CodeBox")
        </div>
    </div>
</div>


<div id="timeline">
    <div class="content-header">
          <h2>Mentions</h2>
    </div>
  <ul id="posts">
       @foreach (var item in Model) {
  
            <li class="stream-item">
                <figure>
                    @if(item.User.ProfileImageUrl != null)
                    {
                        @Html.Image(Url.Content("~/Uploads/" + item.User.ProfileImageUrl + "?width=48&height=48"), "Profile Picture", "48")
                    }
                    else
                    {
                        @Html.Image(Url.Content("~/Uploads/avatar.png" + "?width=48&height=48"), "Profile Picture", "48")
                    }
                </figure>
                <article>
                    <header>
                        <b>@Html.ActionLink(item.User.UserName, "Wall", "Code")</b>
                    </header>
                    <div class="content">
                         @Html.DisplayFor(modelItem => item.Post)
                    </div>
                    <footer>
                        <small>@Html.Timeago(item.PostedOn)</small>
                    </footer>
                </article>
                <div class="clear-fix"></div>
            </li>
 
        }
   </ul>
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Home", new { page }))
</div>

inferse/Views/Code/Profile.cshtml
@model IEnumerable<inferse.Models.Code>
@{
    ViewBag.Title = "Wall";
}
@using inferse.Helpers;
@using PagedList;
@using PagedList.Mvc;
@Styles.Render("~/Content/PagedList.css")

@{
    int userId = Convert.ToInt32(ViewContext.RouteData.Values["id"]);
    int loginUserId = WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name);

    Boolean isMyWall;
    if (userId == loginUserId || userId == 0)
    {
        isMyWall = true;
    }
    else
    {
        isMyWall = false;
    }
}

<div id="dashboard">
     
    <div id="profile-nav" class="module">
        @Html.Partial("ProfileNav")
    </div>
    <div class="module">
        <div id="post-box" class="module-item">
           @Html.Partial("CodeBox")
        </div>
    </div>
</div>

<div id="profile-card" class="module">
    <div id="profile-hedaer" class="module-item">
        <div id="porfile-picture" class="float-left" >
            @if (ViewBag.UserProfile.ProfileImageUrl != null)
            {
                @Html.Image(Url.Content("~/Uploads/" + (string)ViewBag.UserProfile.ProfileImageUrl + "?width=72&height=72"), "Profile Picture", "72")
            }
            else
            {
                @Html.Image(Url.Content("~/Uploads/avatar.png" + "?width=72&height=72"), "Profile Picture", "72")
            }
        </div>
        <div id="profile-details" class="float-left">
            <ul>
                <li><h1>@ViewBag.UserProfile.Name</h1></li>
                <li>@string.Format("{0}" +  @ViewBag.UserProfile.UserName, "@")</li>
                <li>@ViewBag.UserProfile.Location</li>
                <li>@ViewBag.UserProfile.Website</li>
            </ul>
        </div>
    </div>
    <div id="profile-stats" class="module-item">
        <ul>
            <li><a><b>@ViewBag.PostsCount</b>
                <br />
                <small>Posts</small></a></li>
            <li><a><b>@ViewBag.FollowingCount</b>
                <br />
                <small>Following</small></a></li>
            <li><a><b>@ViewBag.FollowerCount</b>
                <br />
                <small>Follower</small></a></li>
            <li id="followship">
                @if(WebMatrix.WebData.WebSecurity.IsAuthenticated && isMyWall== false)
                 {
                    @Html.Partial("Followship")
                 }
            </li>
        </ul>
    </div>
</div>

<div id="timeline">
    <div class="content-header">
        <h2>Timeline</h2>
    </div>
    <ul id="posts">
        @foreach (var item in Model)
        {
  
            <li class="stream-item">
                <figure>
                    @if (item.User.ProfileImageUrl != null)
                    {
                        @Html.Image(Url.Content("~/Uploads/" + item.User.ProfileImageUrl + "?width=48&height=48"), "Profile Picture", "48")
                    }
                    else
                    {
                        @Html.Image(Url.Content("~/Uploads/avatar.png" + "?width=48&height=48"), "Profile Picture", "48")
                    }
                </figure>
                <article>
                    <header>
                        @if(item.User.Name!= null)
                        {
                             <b>@Html.ActionLink(item.User.Name, "Profile", "Code" ,new { id= item.UserId }, null)</b>
                        }
                        <small>@Html.ActionLink(string.Format("{0}" + item.User.UserName,"@"), "Profile", "Code", new { id= item.UserId }, null)</small>
                    </header>
                    <div class="content">
                        @Html.DisplayFor(modelItem => item.Post)
                    </div>
                    <footer>
                        <small>@Html.Timeago(item.PostedOn)</small>
                    </footer>
                </article>
                <div class="clear-fix"></div>
            </li>
 
        }
    </ul>
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Profile", new { page }))
</div>